#!/bin/zsh

ROOT="${HOME}/dotfiles"

ln -snf "${ROOT}/prezto" "${ZDOTDIR:-$HOME}/.zprezto"

cd ROOT
git submodule update --init --recursive

setopt EXTENDED_GLOB
for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N); do
  ln -snf "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
done

for f in .??*
do
    [[ "$f" == ".git" ]] && continue
    [[ "$f" == ".DS_Store" ]] && continue

    rm ~/$f
    ln -snf ~/dotfiles/$f ~/$f
done


